### ISSUE TITLE
Following error raised on Sinistral run

### ISSUE THREAD

**Issue by cvitter** [stacklet/sinistral-cli#50]
>> sinistral run --project "Demo" -d terraform/encryption

Policies executed successfully and returned the correct results:
```
Running 4 policies on 1 resources
check-for-mandatory-tags - terraform.aws*
  Failed
  File: terraform/encryption/sqs.tf:1-19
   1 resource "aws_sqs_queue" "terraform_queue" {                                                                                        
   2   name                      = "terraform-example-queue"                                                                             
   3   delay_seconds             = 90                                                                                                    
   4   max_message_size          = 2048                                                                                                  
   5   message_retention_seconds = 86400                                                                                                 
   6   receive_wait_time_seconds = 10                                                                                                    
   7   redrive_policy = jsonencode({                                                                                                     
   8     deadLetterTargetArn = aws_sqs_queue.terraform_queue_deadletter.arn                                                              
   9     maxReceiveCount     = 4                                                                                                         
  10   })                                                                                                                                
  11                                                                                                                                     
  12   tags = {                                                                                                                          
  13     Environment = "production"                                                                                                      
  14   }                                                                                                                                 
  15                                                                                                                                     
  16   // This resource will fail the Sinistral scan because it's missing a KMS key.                                                     
  17   // Uncomment the line below to make the scan pass.                                                                                
  18   //kms_master_key_id = "alias/aws/sqs"                                                                                             
  19 }                                                                                                                                   

check-encryption - terraform.aws_sqs_queue
  Failed
  Reason: SQS should be encrypted with KMS
  File: terraform/encryption/sqs.tf:1-19
   1 resource "aws_sqs_queue" "terraform_queue" {                                                                                        
   2   name                      = "terraform-example-queue"                                                                             
   3   delay_seconds             = 90                                                                                                    
   4   max_message_size          = 2048                                                                                                  
   5   message_retention_seconds = 86400                                                                                                 
   6   receive_wait_time_seconds = 10                                                                                                    
   7   redrive_policy = jsonencode({                                                                                                     
   8     deadLetterTargetArn = aws_sqs_queue.terraform_queue_deadletter.arn                                                              
   9     maxReceiveCount     = 4                                                                                                         
  10   })                                                                                                                                
  11                                                                                                                                     
  12   tags = {                                                                                                                          
  13     Environment = "production"                                                                                                      
  14   }                                                                                                                                 
  15                                                                                                                                     
  16   // This resource will fail the Sinistral scan because it's missing a KMS key.                                                     
  17   // Uncomment the line below to make the scan pass.                                                                                
  18   //kms_master_key_id = "alias/aws/sqs"                                                                                             
  19 }                                                                                                                                   

Evaluation complete 0.01 seconds -> 2 Failures
                    Summary - By Policy                    
┏━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Severity ┃ Policy                   ┃ Result            ┃
┡━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ high     │ check-encryption         │ 1 failed 0 passed │
│ unknown  │ check-for-mandatory-tags │ 1 failed 0 passed │
└──────────┴──────────────────────────┴───────────────────┘
0 compliant of 1 total, 1 resources have 2 policy violations
```

However following error also followed:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/sinistral", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/stacklet/client/sinistral/cli.py", line 19, in main
    cli(auto_envvar_prefix="SINISTRAL")
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/stacklet/client/sinistral/commands/run.py", line 95, in run
    results.append(int(left_run.invoke(ctx)))
                       ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/c7n_left/cli.py", line 139, in run
    sys.exit(int(runner.run()))
                 ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/c7n_left/core.py", line 271, in run
    self.reporter.on_execution_ended()
  File "/opt/homebrew/lib/python3.12/site-packages/c7n_left/output.py", line 347, in on_execution_ended
    o.on_execution_ended()
  File "/opt/homebrew/lib/python3.12/site-packages/stacklet/client/sinistral/output.py", line 45, in on_execution_ended
    if not r["policy"].get("metadata", {}).get("severity").lower() in (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

The scan does not show up here: https://sinistral.demo.stacklet.io/scans

Scan from this morning does show up. Only difference is the addition of the following policy: https://github.com/stacklet/sinistral-getting-started/blob/main/policies/tagging/mandatory-tags.yml

It appears the error is caused by lack of metadata:severity field in the policy.

Add that field to the policy now and will update with verification

**Comment by cvitter** [comment]
pip3 list says: stacklet-client-sinistral 0.3.0

**Comment by tvansteenburgh** [comment]
Okay, you probably had an older version. v0.3.0 with the fix was released 5 days ago. Going to close this but feel free to re-open it if you can repro with 0.3.0.
